import type { Metadata } from "next";
import "@/app/styles/globals.css";

export const metadata: Metadata = {
  title: "Simas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href='https://unpkg.com/boxicons@latest/css/boxicons.min.css'></link>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}